if(NOT DEFINED TEMPLATE_PATH OR NOT EXISTS "${TEMPLATE_PATH}")
    message(FATAL_ERROR "Pass TEMPLATE_PATH with an existing NSIS script or template")
endif()
file(READ "${TEMPLATE_PATH}" template)
if(template MATCHES "RequestExecutionLevel[ \t]+admin" OR template MATCHES "SetShellVarContext[ \t]+all")
    message(FATAL_ERROR "Island's installer must always use the current user's context")
endif()
foreach(callback ".onInit" "un.onInit")
    string(FIND "${template}" "Function ${callback}\n  SetShellVarContext current" callback_position)
    if(callback_position EQUAL -1)
        message(FATAL_ERROR "${callback} must explicitly select the current user")
    endif()
endforeach()
foreach(value "UninstallString" "DisplayName")
    string(REGEX MATCH "ReadRegStr \\$[01] HKCU [^\n]+ \"${value}\"" lookup "${template}")
    if(NOT lookup)
        message(FATAL_ERROR "The previous install's ${value} must be read from HKCU")
    endif()
endforeach()
if(template MATCHES "ReadRegStr \\$[01] HKLM [^\n]+Uninstall")
    message(FATAL_ERROR "Previous-install detection still uses HKLM")
endif()
string(FIND "${template}" "RequestExecutionLevel user" execution_level_position)
if(execution_level_position EQUAL -1)
    message(FATAL_ERROR "The installer must request user privileges")
endif()
message(STATUS "NSIS per-user installer checks passed: ${TEMPLATE_PATH}")
